gui:
  theme:
    activeBorderColor:
      - "#99d1db"
      - bold
    inactiveBorderColor:
      - "#a5adce"
    optionsTextColor:
      - "#8caaee"
    selectedLineBgColor:
      - "#414559"
    cherryPickedCommitBgColor:
      - "#51576d"
    cherryPickedCommitFgColor:
      - "#99d1db"
    unstagedChangesColor:
      - "#e78284"
    defaultFgColor:
      - "#c6d0f5"
    searchingActiveBorderColor:
      - "#e5c890"
  authorColors:
    "*": "#babbf1"
customCommands:
  - key: "c"
    command: czg
    context: files
    description: Create commit with cz-git
    output: terminal
  - key: "C"
    command: git commit
    context: files
    description: Create commit
    output: terminal
